INSERT INTO URUN_TURU (id, ADI, TUR) VALUES (1, 'Yiyecek', 'YIYECEK');
INSERT INTO URUN_TURU (id, ADI, TUR) VALUES (2,'Icecek','ICECEK');
INSERT INTO URUN_TURU (id, ADI, TUR) VALUES (3,'Giyecek','GIYECEK');
INSERT INTO URUN_TURU (id, ADI, TUR) VALUES (4,'Yakacak','YAKACAK');
INSERT INTO URUN_TURU (id, ADI, TUR) VALUES (5,'Tuketim Malzemesi','TUKETIM_MALZEMESI');
